theme: jekyll-theme-hacker
title: Selfhost AdvaithBot
favicon: https://images.discordapp.net/avatars/398690824721924107/4a5c4e12547c316382ba3b4fabe768cc.png?size=1024
url: https://selfhost.advaithbot.com
